FROM woodpeckerci/woodpecker-agent:next-6bf72cbeaf-alpine

# Build and install plugin-git since it is not included in the agent image
RUN apk add --no-cache \
        git \
        git-lfs \
        go

WORKDIR /tmp
RUN git clone --depth 1 --branch v2.0.3 https://github.com/woodpecker-ci/plugin-git.git

WORKDIR /tmp/plugin-git
ARG GOOS=linux
ARG GOARCH=arm64
ARG CGO_ENABLED=0
ARG GO111MODULE=on
RUN go build -v -a -tags netgo -o /bin/plugin-git

RUN apk del go
RUN rm -rf /tmp/plugin-git

# Install Rust
WORKDIR /

RUN apk add --no-cache \
        ca-certificates \
        gcc

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.69.0

RUN set -eux; \
    apkArch="$(apk --print-arch)"; \
    case "$apkArch" in \
        x86_64) rustArch='x86_64-unknown-linux-musl'; rustupSha256='7aa9e2a380a9958fc1fc426a3323209b2c86181c6816640979580f62ff7d48d4' ;; \
        aarch64) rustArch='aarch64-unknown-linux-musl'; rustupSha256='b1962dfc18e1fd47d01341e6897cace67cddfabf547ef394e8883939bd6e002e' ;; \
        *) echo >&2 "unsupported architecture: $apkArch"; exit 1 ;; \
    esac; \
    url="https://static.rust-lang.org/rustup/archive/1.26.0/${rustArch}/rustup-init"; \
    wget "$url"; \
    echo "${rustupSha256} *rustup-init" | sha256sum -c -; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host ${rustArch}; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version;

RUN rustup self update
RUN rustup update stable
RUN rustup target add thumbv6m-none-eabi

RUN apk add --no-cache \
        libusb-dev \
        libudev-zero-dev \
        musl-dev \
        linux-headers

RUN cargo install probe-run
