FROM gitea/gitea:1.20.5

COPY gitea_startup.sh /setup/
ENTRYPOINT ["/setup/gitea_startup.sh"]

# TODO Add OAuth App for Woodpecker Server by default
# Not currently possible according to
# https://github.com/go-gitea/gitea/issues/8764

# TODO Add the embci-example-repo by default
