version: '3'

networks:
  internal:
    external: false

services:
  gitea:
    build:
      context: gitea
    ports:
      - 3000:3000
    container_name: "gitea"
    restart: "unless-stopped"
    environment:
      USER_UID: "1000"
      USER_GID: "1000"
      USER: "git"
      GITEA__server__DOMAIN: "${IP_ADDRESS}"
      GITEA__server__SSH_DOMAIN: "${IP_ADDRESS}"
      GITEA__server__ROOT_URL: "http://${IP_ADDRESS}:3000/"
      GITEA__webhook__ALLOWED_HOST_LIST: "${IP_ADDRESS}"
      GITEA__security__INSTALL_LOCK: "true"
    volumes:
      - gitea-data:/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - "internal"

  woodpecker-server:
    build:
      context: woodpecker-server
    ports:
      - 8000:8000
    container_name: "woodpecker-server"
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_HOST=http://${IP_ADDRESS}:8000
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://${IP_ADDRESS}:3000
      - WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_LOG_LEVEL=debug
    volumes:
      - woodpecker-server-data:/var/lib/woodpecker/
    networks:
      - "internal"

  woodpecker-agent:
    build:
      context: woodpecker-agent
    container_name: "woodpecker-agent"
    command: agent
    restart: always
    privileged: true
    depends_on:
      - woodpecker-server
      - minio
    environment:
      - WOODPECKER_BACKEND=local
      - WOODPECKER_SERVER=woodpecker-server:9000
      - WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}
      - WOODPECKER_LOG_LEVEL=debug
      - DEBUG_PROBE_1_SERIAL=${DEBUG_PROBE_1_SERIAL}
      - MINIO_SERVER=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - "internal"

  minio:
    build:
      context: minio
    ports:
      - 9000:9000
      - 9001:9001
    container_name: "minio"
    volumes:
      - minio_storage:/data
    command: server --console-address ":9001" /data
    networks:
      - "internal"

volumes:
  woodpecker-server-data:
  gitea-data:
  minio_storage:
